### ISSUE TITLE
想知道这个文档是不是跟配置不匹配

### ISSUE THREAD

**Issue by HerbertHe** [wangchucheng/hugo-eureka-docs#2]
- 主页配置部分，即使按照文档来也还是这样的

![image](https://user-images.githubusercontent.com/30955264/112715580-dcc37380-8e95-11eb-8877-8d0e59e6496e.png)

**试了很多次，还是没法通过直接配置更新主页**

- 主页配置部分有错误，目录结构不对

[新建小组件](https://www.wangchucheng.com/zh/docs/hugo-eureka/homepage-configuration/#%E6%96%B0%E5%BB%BA%E5%B0%8F%E7%BB%84%E4%BB%B6) 命令不正确

如果是默认配置的话，应该改成下面这样目录结构才没问题

```bash
hugo new -k widgets/pages homepage/<your-name.md>
```

多语言的情况下，也应该是这样的

```bash
hugo new -k widgets/pages zh/homepage/<your-name.md>
```

- 在hugo module使用情况下，项目根目录的 `archetypes` 这个目录优先级会比主题的要高

**应当在文档中标注删掉 `archetypes` 目录，并且声明可通过利用该目录的高优先级覆盖主题不需要的FrontMatter中的属性**

- 一个**demo**会比文档更好一些

**Comment by wangchucheng** [comment]
在任何情况下项目根目录下的同名文件优先级都高于主题目录下的内容。这是一个Hugo的逻辑使用户可以自定义模板。

对于新建小组件的命令，单一语言的文档确实需要补充。但多语言的命令在完成文档时是进行过测试的，可能Hugo在之后的版本中更改过逻辑，我将在近期进行测试。

archetypes的问题，根据我之前的测试，自动生成的目录中不包含和widgets文件夹里的内容同路径及同名的文件，因此不会生成失败。

主题中的exampleSite即为项目demo源码。

祝好！
